prog1 : prog1.c
	gcc -Wall -g -o prog1 prog1.c

prog2 : prog2.c
	gcc -Wall -g -o prog2 prog2.c	

prog3 : prog3.c
	gcc -Wall -g -o prog3 prog3.c	
		
prog4 : prog4.c
	gcc -Wall -g -o prog4 prog4.c	
	
prog5 : prog5.c
	gcc -Wall -g -o prog5 prog5.c	
		
clean :
	-rm prog1 prog2 prog3 prog4 prog5